export const SEARCH_FOCUS = 'header/SEARCH_FOCUS'
export const SEARCH_BLUR = 'header/SEARCH_BLUR'
export const CHAGE_LIST = 'header/CHAGE_LIST'
export const MOUSE_ENTER = 'header/MOUSE_ENTER'
export const MOUSE_LEAVE = 'hander/MOUSE_LVAVE'
export const CHANGE_PAGE_LIST = 'hander/CHANGE_PAGE_LIST'
